# For a list of block IDs see https://minecraft.fandom.com/wiki/Java_Edition_data_values#Blocks
# For a list of item IDs see https://minecraft.fandom.com/wiki/Java_Edition_data_values#Items
disabledMaterials:
  # - diamond

# For a list of enchantment IDs see https://minecraft.fandom.com/wiki/Java_Edition_data_values#Enchantments
disabledEnchantments:
  # - mending