main: com.abbydiode.tradedisabler.App
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: https://github.com/abbydiode
website: ${project.url}
api-version: 1.18
